### ISSUE TITLE
Build fails during cmake

### ISSUE THREAD

**Issue by jefffhaynes** [edgeimpulse/firmware-nrf52840-5340-dk#2]
C:\Users\feedy\source\repos\firmware-nrf52840-5340-dk>west build -b nrf52840dk_nrf52840
-- west build: generating a build system
Including boilerplate (Zephyr base): C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/zephyr/cmake/app/boilerplate.cmake
-- Application: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk
-- Zephyr version: 2.5.99 (C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/zephyr)
-- Found Python3: C:/Python39/python.exe (found suitable exact version "3.9.2") found components: Interpreter
-- Found west (found suitable version "0.10.0", minimum required is "0.7.1")
-- Board: nrf52840dk_nrf52840
-- Cache files will be written to: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/zephyr/.cache
-- Found toolchain: gnuarmemb (C:/gnu_arm_embedded)
-- Found BOARD.dts: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
-- Found devicetree overlay: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/boards/nrf52840dk_nrf52840.overlay
-- Generated zephyr.dts: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/build/zephyr/include/generated/device_extern.h
Parsing C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/zephyr/Kconfig
Loaded configuration 'C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840_defconfig'
Merged configuration 'C:/Users/feedy/source/repos/firmware-nrf52840-5340-dk/prj.conf'

error: LOG_IMMEDIATE (defined at subsys/logging\Kconfig.mode:47) is assigned in a configuration
file, but is not directly user-configurable (has no prompt). It gets its value indirectly from other
symbols. See http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_LOG_IMMEDIATE.html and/or
look up LOG_IMMEDIATE in the menuconfig/guiconfig interface. The Application Development Primer,
Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be
helpful too.

CMake Error at zephyr/cmake/kconfig.cmake:265 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  zephyr/cmake/app/boilerplate.cmake:553 (include)
  zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: 'C:\Program Files\CMake\bin\cmake.EXE' '-DWEST_PYTHON=c:\python39\python.exe' '-BC:\Users\feedy\source\repos\firmware-nrf52840-5340-dk\build' '-SC:\Users\feedy\source\repos\firmware-nrf52840-5340-dk' -GNinja -DBOARD=nrf52840dk_nrf52840

**Comment by robin-noomi** [comment]
I have same issue

**Comment by luisomoreau** [comment]
Please see this [thread](https://forum.edgeimpulse.com/t/build-error-on-firmware-nrf52840-5340-dk-using-zephyr/2192/2?u=louis) on Edge Impulse forum while waiting for an update on this repository
