### ISSUE TITLE
Error in the build commands

### ISSUE THREAD

**Issue by NordicMatt** [edgeimpulse/firmware-nrf52840-5340-dk#3]
This line should read:
$ west build -b nrf5340dk_nrf5340_cpuappns

**Comment by janjongboom** [comment]
@NordicMatt Sorry didn't have notifications enabled for this repo. Why exactly though? The current build command is how we build for the nRF5340 DK both in our integration tests and in the Studio and this works as-is.

**Comment by VojislavM** [comment]
the application is build as a secure application so the command for building is:
```
$ west build -b nrf5340dk_nrf5340_cpuapp
```
