### ISSUE TITLE
Dropping frames?

### ISSUE THREAD

**Issue by jefffhaynes** [edgeimpulse/firmware-nrf52840-5340-dk#4]
I've been playing around a lot with the microphone implementation for the nrf52/53.  It seems to me like "frames" (PDM updates) are probably being dropped between inferences.  I'm still trying to prove this but one thing that seems off is the comment at the end of this line:

https://github.com/edgeimpulse/firmware-nrf52840-5340-dk/blob/6a2296ae702b3ea0512a907bae7b149640905ad6/edge-impulse/ingestion-sdk-platform/NordicSemi-nrf52/sensors/ei_microphone.cpp#L54

which seems to imply that this calculation comes out to 4096 when in fact this calculation comes out to 512.  An insufficient buffer here would potentially explain this frame drop so I'm wondering if this is the culprit.  Can anyone explain the presence of this comment and whether it is the comment or the code that's wrong?

EDIT: Does this value need to change based on DSP/NN latency?

**Comment by automatiek** [comment]
Hi Jeff, 
The buffer size in line you displayed is used for the raw buffer that is filled by the PDM pheripheral and remains the same for all model lengths. It is indeed correct that frames are dropped in between inferences when running normal mode:
```
$ edge-impulse-run-impulse
```
You can run audio in continuous mode by adding the `--continuous` flag:
```
$ edge-impulse-run-impulse --continuous
```
In this mode samples are still being captured during inference. You can read more about this in our docs: https://docs.edgeimpulse.com/docs/continuous-audio-sampling

Hopefully this solves your issue

**Comment by jefffhaynes** [comment]
I am running in continuous mode, but I believe frames are still being dropped when the DSP/NN latency is too high.  This stands to reason as for some arbitrary latency, the time to update the PDM buffer will be too great.  I think the implementation is also somewhat confusing since "double buffering" is happening in two locations but in one it doesn't seem to actually do anything as the continuous update is serial in nature.  Possibly this behavior is giving the impression that data is less likely to be lost than it actually is.

**Comment by automatiek** [comment]
Ah, now I see what mean. 

Normally the `inference.buffer[]` is filled with new samples while the other `inference.buffer[]` is used for inference. And one of the `pdm_buffer_temp[]` buffer is copied to the `inference.buffer[]` while the other is being filled with new data. 

I see in this case, copying audio to the `inference.buffer[]` is blocked. I will look into this. In continuous inference mode it would make sense to set the `AUDIO_DSP_SAMPLE_BUFFER_SIZE` to the slice size of the model: `EI_CLASSIFIER_SLICE_SIZE`

**Comment by jefffhaynes** [comment]
That might help.  I think ultimately it will likely be possible to get into a state where stuff is being dropped.  The best bet may simply be to detect this and report on it or something.

**Comment by automatiek** [comment]
Hi @jefffhaynes ,

We've added a fix for sampling data in continuous inference and a detection on sample buffer overrun.
