### ISSUE TITLE
nRF5340 Audio

### ISSUE THREAD

**Issue by mcernak** [edgeimpulse/firmware-nrf52840-5340-dk#5]
Hello
Does this firmware support also nRF5340 Audio DK?
https://www.nordicsemi.com/Products/Development-hardware/nRF5340-Audio-DK/
When I flash current firmware and connect the board, I get
[SER] Connecting to /dev/tty.usbserial-403670
[SER] Serial is connected, trying to read config...
[SER] Failed to get info off device Timeout when waiting for >  (timeout: 5000) onConnected

**Comment by VojislavM** [comment]
Hi, the firmware currently **does not support** audio kit. The supported boards are nRF52840DK and nRF5340DK. This is the reason you are not getting the response on the device UART.

**Comment by VojislavM** [comment]
but you’re free to modify the code to make it work. You can point him at our example standalone repo for Zephyr https://github.com/edgeimpulse/example-standalone-inferencing-zephyr to start with and use the nrf52840 / nrf53840 firmware for reference to add sensors and communication


currently you can see that for UART communication we are using `uart0` from the device tree. This could be a starting point to check if it matches the UART you are trying to use. 
https://github.com/edgeimpulse/firmware-nrf52840-5340-dk/blob/81692f329379e1e0b76ddee60cc50a734ba5127e/edge-impulse/ingestion-sdk-platform/NordicSemi-nrf52/ei_device_nordic_nrf52.cpp#L756

**Comment by automatiek** [comment]
closing inactive / resolved issue
